version: "3.8"
services:
  StokersWebsite:
    image: ${DOCKER_REGISTRY-}stokersapi
    build:
      context: ./StokersWebsiteDataAPI
      dockerfile: ./WebsiteStokers/Dockerfile
    ports:
      - 5003:5003
    environment:
      ASPNETCORE_ConnectionStrings__StokersConnection:"Server = stokersdatatransferservice_db_1; User = sa; Password = R9QgoT#Pm8; Database = Stokers"
    depends_on:
      - db
  
  StokersReactWebsite:
    image: ${DOCKER_REGISTRY-}stokersreactwebsite
    ports:
      - 4040:4040
    depends_on: 
      - StokersWebsite

  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
        SA_PASSWORD: "R9QgoT#Pm8"
        ACCEPT_EULA: "Y"
    volumes:
      - ./mssql-db:/var/opt/mssql/data
    ports:
      - 1433:1433
