version: "3.8"
services:
  StokersWebsite:
    image: rensvlooswijk/stokersdatatransferservice:main
    ports:
      - 5003:5003
    depends_on:
      - db
    environment:
      ConnectionStrings__UserContext: "Server=db;Database=stokersdatatransferservice_db;User=sa;Password=R9QgoT#Pm8;"


  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
        SA_PASSWORD: "R9QgoT#Pm8"
        ACCEPT_EULA: "Y"
    volumes:
      - ./mssql-db:/var/opt/mssql/data
    ports:
      - 1433:1433