version: "3.8"
services:
  StokersWebsite:
    image: ${DOCKER_REGISTRY-}stokersapi
    build:
      context: ./StokersWebsiteDataAPI
      dockerfile: ./WebsiteStokers/Dockerfile
    ports:
      - 5003:5003
    depends_on:
      - db

  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
        SA_PASSWORD: "R9QgoT#Pm8"
        ACCEPT_EULA: "Y"
    volumes:
      - ./mssql-db:/var/opt/mssql/data
    ports:
      - 1433:1433